site_name: ZenovateX Documentation
site_url: https://zenovatex.readthedocs.io
theme:
  name: 'material'
  font:
    text: 'Roboto' 

plugins:
  - search
  - awesome-pages
  - mkdocstrings

markdown_extensions:
  - codehilite

nav:
  - Home: index.md