site_name: ZenovateX Documentation
site_url: https://zenovatex.readthedocs.io
theme:
  name: 'readthedocs'


plugins:
  - search
  - awesome-pages
  - mkdocstrings

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Notes: 01_notes/notes.md
